import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebars configuration for the Reduit documentation site.
 *
 * `guides` is hand-authored content copied verbatim into docs-generated/
 * by scripts/transform-content.js. `specs` and `decisions` are generated
 * from ../docs/openspec/specs and ../docs/adrs by the transform scripts.
 * The _category_.json files in each directory control ordering and labels.
 */
const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
  specsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'specs',
    },
  ],
  decisionsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'decisions',
    },
  ],
};

export default sidebars;
