import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebars configuration for the Reduit documentation site.
 *
 * The `guides` sidebar was removed on 2026-07-04 — the relay-era guides it
 * autogenerated (getting-started/configuration/reverse-proxy/apple-mail/
 * claude-code) were retired along with the multi-user OIDC relay design
 * (ADR-0012) and the HTMX web UI (ADR-0025). Overview.md carries a "docs
 * are being rebuilt" landing page pointing at the repo's ADRs/specs as the
 * current source of truth. The guides sidebar will be reintroduced once
 * the TUI ships.
 *
 * `specs` and `decisions` are generated from ../docs/openspec/specs and
 * ../docs/adrs by the transform scripts. The _category_.json files in each
 * directory control ordering and labels.
 */
const sidebars: SidebarsConfig = {
  specsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'specs',
    },
  ],
  decisionsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'decisions',
    },
  ],
};

export default sidebars;
